apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  labels:
    {{- include "k8s-pod-restart-info-collector.labels" . | nindent 4 }}
data:
  collector.sh: |-
{{ .Files.Get "collector.sh" | indent 4}}
